# Wrangler configuration for Cloudflare Pages deployment
name = "chemistry-ai"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

# Custom domain configuration will be set in Cloudflare dashboard
# Domain: chemistryai.online